# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(805, 606)
        MainWindow.setMinimumSize(QtCore.QSize(805, 606))
        MainWindow.setMaximumSize(QtCore.QSize(805, 606))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(10, 70, 381, 211))
        self.graphicsView.setObjectName("graphicsView")
        self.pb_Browse = QtWidgets.QPushButton(self.centralwidget)
        self.pb_Browse.setGeometry(QtCore.QRect(10, 290, 89, 25))
        self.pb_Browse.setObjectName("pb_Browse")
        self.pb_Read = QtWidgets.QPushButton(self.centralwidget)
        self.pb_Read.setGeometry(QtCore.QRect(300, 290, 89, 25))
        self.pb_Read.setObjectName("pb_Read")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_2.setGeometry(QtCore.QRect(410, 70, 381, 211))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 330, 781, 181))
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(410, 290, 89, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(700, 290, 89, 25))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(560, 290, 89, 25))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(350, 520, 101, 25))
        self.pushButton_6.setObjectName("pushButton_6")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 50, 281, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(410, 50, 281, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(150, 10, 491, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 805, 24))
        self.menubar.setObjectName("menubar")
        self.menuAccount = QtWidgets.QMenu(self.menubar)
        self.menuAccount.setObjectName("menuAccount")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionName = QtWidgets.QAction(MainWindow)
        self.actionName.setObjectName("actionName")
        self.actionSignOut = QtWidgets.QAction(MainWindow)
        self.actionSignOut.setObjectName("actionSignOut")
        self.menuAccount.addSeparator()
        self.menuAccount.addSeparator()
        self.menuAccount.addAction(self.actionSignOut)
        self.menubar.addAction(self.menuAccount.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Text Recognition"))
        self.pb_Browse.setText(_translate("MainWindow", "Browse"))
        self.pb_Read.setText(_translate("MainWindow", "Read"))
        self.pushButton_3.setText(_translate("MainWindow", "Enable"))
        self.pushButton_4.setText(_translate("MainWindow", "Read"))
        self.pushButton_5.setText(_translate("MainWindow", "Capture"))
        self.pushButton_6.setText(_translate("MainWindow", "Clear Text"))
        self.label.setText(_translate("MainWindow", "Browse an Image"))
        self.label_2.setText(_translate("MainWindow", "Capture Image via Webcam"))
        self.menuAccount.setTitle(_translate("MainWindow", "Account"))
        self.actionName.setText(_translate("MainWindow", "Name"))
        self.actionSignOut.setText(_translate("MainWindow", "Sign Out"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

